---
vars_files:
- /home/sysadmin/ansible/vault.yml
- /home/sysadmin/ansible/edge.yml


become_method: runas
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_port: 5985
ansible_winrm_transport: ntlm
#### LOCAL ansible user AUTH SETTINGS BELOW ####
ansible_user: azurestandard.com\admin
ansible_become_pass:  "{{ win_pw }}"
ansible_password:  "{{ win_pw }}"
become_user: azurestandard.com\admin
#ansible_winrm_transport: basic
#### Azure user local auth settings, will also work with administrator ####
#ansible_user: Azure
#ansible_become_pass:  "{{ win_password }}"
#ansible_password:  "{{ win_password }}"
#become_user: Azure
#ansible_winrm_transport: ntlm
